-- =============================================
-- 小米之家门店管理系统 - 数据库初始化脚本
-- 数据库: xiaomi_store
-- =============================================

CREATE DATABASE IF NOT EXISTS xiaomi_store DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE xiaomi_store;

-- 用户信息表
CREATE TABLE IF NOT EXISTS `USER_INFO` (
  `TID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `USER_ID` BIGINT(20) NOT NULL COMMENT '用户业务ID',
  `USER_NAME` VARCHAR(50) NOT NULL COMMENT '用户名',
  `PASSWORD` VARCHAR(100) NOT NULL COMMENT '密码',
  `ROLE_ID` BIGINT(20) COMMENT '角色ID',
  `STATUS` TINYINT(4) NOT NULL DEFAULT 0 COMMENT '用户状态：0-正常，1-禁用',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`TID`),
  UNIQUE KEY `UK_USER_NAME` (`USER_NAME`) COMMENT '用户名唯一索引',
  KEY `IDX_ROLE_ID` (`ROLE_ID`) COMMENT '角色ID索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户信息表';

-- 角色信息表
CREATE TABLE IF NOT EXISTS `ROLE_INFO` (
  `TID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `ROLE_ID` BIGINT(20) NOT NULL COMMENT '角色业务ID',
  `ROLE_NAME` VARCHAR(50) NOT NULL COMMENT '角色名称',
  `DESCRIPTION` VARCHAR(200) COMMENT '角色描述',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`TID`),
  UNIQUE KEY `UK_ROLE_NAME` (`ROLE_NAME`) COMMENT '角色名称唯一索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='角色信息表';

-- 权限信息表
CREATE TABLE IF NOT EXISTS `PERMISSION_INFO` (
  `TID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `PERMISSION_ID` BIGINT(20) NOT NULL COMMENT '权限业务ID',
  `PERMISSION_CODE` VARCHAR(50) NOT NULL COMMENT '权限编码',
  `PERMISSION_NAME` VARCHAR(100) NOT NULL COMMENT '权限名称',
  `DESCRIPTION` VARCHAR(200) COMMENT '权限描述',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`TID`),
  UNIQUE KEY `UK_PERMISSION_CODE` (`PERMISSION_CODE`) COMMENT '权限编码唯一索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='权限信息表';

-- 角色权限关联表
CREATE TABLE IF NOT EXISTS `ROLE_PERMISSION_REL` (
  `TID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `ROLE_ID` BIGINT(20) NOT NULL COMMENT '角色ID',
  `PERMISSION_ID` BIGINT(20) NOT NULL COMMENT '权限ID',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`TID`),
  KEY `IDX_ROLE_ID` (`ROLE_ID`) COMMENT '角色ID索引',
  KEY `IDX_PERMISSION_ID` (`PERMISSION_ID`) COMMENT '权限ID索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='角色权限关联表';

-- 商品信息表
CREATE TABLE IF NOT EXISTS `PRODUCT_INFO` (
  `TID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `PRODUCT_ID` BIGINT(20) NOT NULL COMMENT '商品业务ID',
  `PRODUCT_CODE` VARCHAR(30) NOT NULL COMMENT '商品编码',
  `PRODUCT_NAME` VARCHAR(100) NOT NULL COMMENT '商品名称',
  `CATEGORY_ID` BIGINT(20) NOT NULL COMMENT '分类ID',
  `PRICE` DECIMAL(10,2) NOT NULL COMMENT '商品价格',
  `STOCK_QUANTITY` INT NOT NULL DEFAULT 0 COMMENT '库存数量',
  `STATUS` TINYINT(4) NOT NULL DEFAULT 0 COMMENT '商品状态：0-上架，1-下架',
  `DESCRIPTION` TEXT COMMENT '商品描述',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`TID`),
  UNIQUE KEY `UK_PRODUCT_CODE` (`PRODUCT_CODE`) COMMENT '商品编码唯一索引',
  KEY `IDX_CATEGORY_ID` (`CATEGORY_ID`) COMMENT '分类ID索引',
  KEY `IDX_STATUS` (`STATUS`) COMMENT '商品状态索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品信息表';

-- 商品分类信息表
CREATE TABLE IF NOT EXISTS `CATEGORY_INFO` (
  `TID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `CATEGORY_ID` BIGINT(20) NOT NULL COMMENT '分类业务ID',
  `CATEGORY_NAME` VARCHAR(50) NOT NULL COMMENT '分类名称',
  `PARENT_ID` BIGINT(20) COMMENT '父分类ID',
  `LEVEL` TINYINT(4) NOT NULL DEFAULT 1 COMMENT '分类层级',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`TID`),
  UNIQUE KEY `UK_CATEGORY_NAME` (`CATEGORY_NAME`) COMMENT '分类名称唯一索引',
  KEY `IDX_PARENT_ID` (`PARENT_ID`) COMMENT '父分类ID索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品分类信息表';

-- 商品入库信息表
CREATE TABLE IF NOT EXISTS `STOCK_IN_INFO` (
  `TID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `STOCK_IN_ID` BIGINT(20) NOT NULL COMMENT '入库业务ID',
  `PRODUCT_ID` BIGINT(20) NOT NULL COMMENT '商品ID',
  `QUANTITY` INT NOT NULL COMMENT '入库数量',
  `OPERATOR_ID` BIGINT(20) NOT NULL COMMENT '操作人ID',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`TID`),
  KEY `IDX_PRODUCT_ID` (`PRODUCT_ID`) COMMENT '商品ID索引',
  KEY `IDX_OPERATOR_ID` (`OPERATOR_ID`) COMMENT '操作人ID索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品入库信息表';

-- 商品出库信息表
CREATE TABLE IF NOT EXISTS `STOCK_OUT_INFO` (
  `TID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `STOCK_OUT_ID` BIGINT(20) NOT NULL COMMENT '出库业务ID',
  `PRODUCT_ID` BIGINT(20) NOT NULL COMMENT '商品ID',
  `QUANTITY` INT NOT NULL COMMENT '出库数量',
  `OPERATOR_ID` BIGINT(20) NOT NULL COMMENT '操作人ID',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`TID`),
  KEY `IDX_PRODUCT_ID` (`PRODUCT_ID`) COMMENT '商品ID索引',
  KEY `IDX_OPERATOR_ID` (`OPERATOR_ID`) COMMENT '操作人ID索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商品出库信息表';

-- 订单信息表
CREATE TABLE IF NOT EXISTS `ORDER_INFO` (
  `TID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `ORDER_ID` BIGINT(20) NOT NULL COMMENT '订单业务ID',
  `ORDER_NO` VARCHAR(64) NOT NULL COMMENT '订单号',
  `USER_ID` BIGINT(20) NOT NULL COMMENT '用户ID',
  `AMOUNT` DECIMAL(10,2) NOT NULL COMMENT '订单金额',
  `STATUS` TINYINT(4) NOT NULL DEFAULT 0 COMMENT '订单状态：0-待支付，1-已支付，2-已取消',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`TID`),
  UNIQUE KEY `UK_ORDER_NO` (`ORDER_NO`) COMMENT '订单号唯一索引',
  KEY `IDX_USER_ID` (`USER_ID`) COMMENT '用户ID索引',
  KEY `IDX_STATUS` (`STATUS`) COMMENT '订单状态索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单信息表';

-- 订单明细信息表
CREATE TABLE IF NOT EXISTS `ORDER_ITEM_INFO` (
  `TID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `ORDER_ITEM_ID` BIGINT(20) NOT NULL COMMENT '订单明细业务ID',
  `ORDER_ID` BIGINT(20) NOT NULL COMMENT '订单ID',
  `PRODUCT_ID` BIGINT(20) NOT NULL COMMENT '商品ID',
  `QUANTITY` INT NOT NULL COMMENT '数量',
  `UNIT_PRICE` DECIMAL(10,2) NOT NULL COMMENT '单价',
  `TOTAL_PRICE` DECIMAL(10,2) NOT NULL COMMENT '小计',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`TID`),
  KEY `IDX_ORDER_ID` (`ORDER_ID`) COMMENT '订单ID索引',
  KEY `IDX_PRODUCT_ID` (`PRODUCT_ID`) COMMENT '商品ID索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单明细信息表';

-- 会员信息表
CREATE TABLE IF NOT EXISTS `MEMBER_INFO` (
  `TID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `MEMBER_ID` BIGINT(20) NOT NULL COMMENT '会员业务ID',
  `PHONE` VARCHAR(20) NOT NULL COMMENT '手机号',
  `NAME` VARCHAR(50) NOT NULL COMMENT '姓名',
  `BIRTHDAY` DATE COMMENT '生日',
  `MEMBER_CARD_NO` VARCHAR(20) NOT NULL COMMENT '会员卡号',
  `POINTS` INT NOT NULL DEFAULT 0 COMMENT '积分',
  `LEVEL` TINYINT(4) NOT NULL DEFAULT 1 COMMENT '会员等级',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`TID`),
  UNIQUE KEY `UK_PHONE` (`PHONE`) COMMENT '手机号唯一索引',
  UNIQUE KEY `UK_MEMBER_CARD_NO` (`MEMBER_CARD_NO`) COMMENT '会员卡号唯一索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会员信息表';

-- 会员消费记录表
CREATE TABLE IF NOT EXISTS `MEMBER_CONSUME_RECORD` (
  `TID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `RECORD_ID` BIGINT(20) NOT NULL COMMENT '消费记录业务ID',
  `MEMBER_ID` BIGINT(20) NOT NULL COMMENT '会员ID',
  `ORDER_ID` BIGINT(20) NOT NULL COMMENT '订单ID',
  `CONSUME_AMOUNT` DECIMAL(10,2) NOT NULL COMMENT '消费金额',
  `POINTS_GAINED` INT NOT NULL DEFAULT 0 COMMENT '获得积分',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`TID`),
  KEY `IDX_MEMBER_ID` (`MEMBER_ID`) COMMENT '会员ID索引',
  KEY `IDX_ORDER_ID` (`ORDER_ID`) COMMENT '订单ID索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='会员消费记录表';

-- 库存操作日志表
CREATE TABLE IF NOT EXISTS `STOCK_LOG_INFO` (
  `TID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `LOG_ID` BIGINT(20) NOT NULL COMMENT '日志业务ID',
  `PRODUCT_ID` BIGINT(20) NOT NULL COMMENT '商品ID',
  `OPERATOR_ID` BIGINT(20) NOT NULL COMMENT '操作人ID',
  `OPERATION_TYPE` TINYINT(4) NOT NULL COMMENT '操作类型：0-入库，1-出库',
  `QUANTITY` INT NOT NULL COMMENT '变动数量',
  `REASON` VARCHAR(200) COMMENT '操作原因',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`TID`),
  KEY `IDX_PRODUCT_ID` (`PRODUCT_ID`) COMMENT '商品ID索引',
  KEY `IDX_OPERATOR_ID` (`OPERATOR_ID`) COMMENT '操作人ID索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='库存操作日志表';

-- 库存预警规则表
CREATE TABLE IF NOT EXISTS `STOCK_WARNING_RULE` (
  `TID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `RULE_ID` BIGINT(20) NOT NULL COMMENT '规则业务ID',
  `PRODUCT_ID` BIGINT(20) NOT NULL COMMENT '商品ID',
  `MIN_STOCK` INT NOT NULL DEFAULT 0 COMMENT '最低库存阈值',
  `WARNING_METHOD` VARCHAR(20) NOT NULL COMMENT '预警方式',
  `ENABLED` TINYINT(4) NOT NULL DEFAULT 1 COMMENT '是否启用：0-否，1-是',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`TID`),
  KEY `IDX_PRODUCT_ID` (`PRODUCT_ID`) COMMENT '商品ID索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='库存预警规则表';

-- =============================================
-- 初始化完成
-- =============================================
